// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UoW.LOG;

namespace UoW.LOG.Migrations
{
    [DbContext(typeof(UoWDbLogContext))]
    [Migration("20210331093011_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("UoW.LOG.Models.Durumlar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DurumAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("durumlars");
                });

            modelBuilder.Entity("UoW.LOG.Models.Islemler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Eklenme")
                        .HasColumnType("datetime2");

                    b.Property<string>("IslemAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("islemlers");
                });

            modelBuilder.Entity("UoW.LOG.Models.Loglar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurumID")
                        .HasColumnType("int");

                    b.Property<int>("IslemID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Saat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("YoneticiID")
                        .HasColumnType("int");

                    b.Property<int?>("durumlarID")
                        .HasColumnType("int");

                    b.Property<int?>("islemlerID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("YoneticiID");

                    b.HasIndex("durumlarID");

                    b.HasIndex("islemlerID");

                    b.ToTable("logs");
                });

            modelBuilder.Entity("UoW.LOG.Models.Yonetici", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("yoneticilers");
                });

            modelBuilder.Entity("UoW.LOG.Models.Loglar", b =>
                {
                    b.HasOne("UoW.LOG.Models.Yonetici", "yonetici")
                        .WithMany("loglars")
                        .HasForeignKey("YoneticiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UoW.LOG.Models.Durumlar", "durumlar")
                        .WithMany("loglars")
                        .HasForeignKey("durumlarID");

                    b.HasOne("UoW.LOG.Models.Islemler", "islemler")
                        .WithMany("loglars")
                        .HasForeignKey("islemlerID");

                    b.Navigation("durumlar");

                    b.Navigation("islemler");

                    b.Navigation("yonetici");
                });

            modelBuilder.Entity("UoW.LOG.Models.Durumlar", b =>
                {
                    b.Navigation("loglars");
                });

            modelBuilder.Entity("UoW.LOG.Models.Islemler", b =>
                {
                    b.Navigation("loglars");
                });

            modelBuilder.Entity("UoW.LOG.Models.Yonetici", b =>
                {
                    b.Navigation("loglars");
                });
#pragma warning restore 612, 618
        }
    }
}
